defmodule AshStorage.TestRepo.Migrations.RestrictFkLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:restrict_fk_test_posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
    end

    create table(:restrict_fk_test_blobs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:filename, :text, null: false)
      add(:content_type, :text)
      add(:byte_size, :bigint)
      add(:checksum, :text)
      add(:service_name, :text, null: false)
      add(:service_opts, :map, default: %{})
      add(:metadata, :map, default: %{})
      add(:analyzers, :map, default: %{})
      add(:pending_purge, :boolean, null: false, default: false)
      add(:pending_analyzers, :boolean, null: false, default: false)
      add(:pending_variants, :boolean, null: false, default: false)

      add(
        :variant_of_blob_id,
        references(:restrict_fk_test_blobs,
          column: :id,
          name: "restrict_fk_test_blobs_variant_of_blob_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(:variant_name, :text)
      add(:variant_digest, :text)
    end

    create table(:restrict_fk_test_attachments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)

      add(
        :blob_id,
        references(:restrict_fk_test_blobs,
          column: :id,
          name: "restrict_fk_test_attachments_blob_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :restrict_fk_test_post_id,
        references(:restrict_fk_test_posts,
          column: :id,
          name: "restrict_fk_test_attachments_restrict_fk_test_post_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:restrict_fk_test_attachments, "restrict_fk_test_attachments_blob_id_fkey"))

    drop(
      constraint(
        :restrict_fk_test_attachments,
        "restrict_fk_test_attachments_restrict_fk_test_post_id_fkey"
      )
    )

    drop(table(:restrict_fk_test_attachments))

    drop(constraint(:restrict_fk_test_blobs, "restrict_fk_test_blobs_variant_of_blob_id_fkey"))

    drop(table(:restrict_fk_test_blobs))

    drop(table(:restrict_fk_test_posts))
  end
end
